# --- Basic options --- #

# Name of website
title: Recipe Project Page

# Short description of your site
description: BAI Recipe Project Github Page

# Your name to show in the footer
author: Justyna Pietryga, Michał Rosicki, Marek Nalepka

# --- List of links in the navigation bar --- #

navbar-links:
  About Me: "aboutme"
  Resources:
    - Beautiful Jekyll: "https://beautifuljekyll.com"
    - Learn markdown: "https://www.markdowntutorial.com/"
  Author's home: "https://deanattali.com"

# --- Logo --- #

# Image to show in the navigation bar - works best with a square image
# Remove this parameter if you don't want an image in the navbar
avatar: "favicon.ico"

# By default, the image is cut into a circle. You can disable this behaviour here.
round-avatar: true

# If you want to have an image logo in the top-left corner instead of the title text,
# then specify the following parameter
title-img: "favicon.ico"

theme: jekyll-theme-cayman